"""Deterministic itinerary generator.

Turns ranked places from the dataset, the trip constraints, and the weather report into a
day-by-day plan with time-of-day blocks and costs. All names and prices come from the
dataset; nothing here is generated by a language model.

Time model: the trip starts at 07:00 on day 1 and must be back home by the end of the last
day. Outbound and return travel times come from the dataset, so the time actually spent at
the destination is the gap between arrival and departure. Each day is filled by placing
meals and activity slots sequentially inside the hours available that day.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import date, timedelta

from pydantic import BaseModel, Field, field_validator

from agent.data import find_origin, get_destination
from agent.errors import ToolError
from agent.models import (
    INTERESTS, MAX_TRAVELERS, MAX_TRIP_DAYS, Attraction, Block, CostLines, Day, DayWeather,
    Destination, Itinerary, Pace, Restaurant, Tier,
)
from agent.tools.destination_search import PlaceMatches
from agent.tools.weather import WeatherReport

TIER_ORDER: dict[str, int] = {"budget": 0, "mid": 1, "premium": 2}
TIER_LABEL = {"budget": "budget", "mid": "mid-range", "premium": "premium"}
FULL_DAY_HOURS = 5.0
DAY_START, DAY_END = 8.0, 22.0


@dataclass(frozen=True)
class Rung:
    transport: str  # "fast" or "cheap"
    stay: Tier
    paid_activities: bool


# Comfort-descending ladder. The budget loop moves down it until the plan fits.
LADDER: tuple[Rung, ...] = (
    Rung("fast", "premium", True),
    Rung("fast", "mid", True),
    Rung("cheap", "mid", True),
    Rung("cheap", "budget", True),
    Rung("cheap", "budget", False),
)
LAST_RUNG = len(LADDER) - 1
PREMIUM_PER_PERSON_DAY = 7000.0


def initial_rung(budget: float | None, days: int, travelers: int) -> int:
    if budget and budget / (days * travelers) >= PREMIUM_PER_PERSON_DAY:
        return 0
    return 1


@dataclass(frozen=True)
class SlotSpec:
    tod: str
    start: float
    cap: float


# (breakfast, lunch, dinner) nominal start times and the activity slots for each pace
PACE_PLAN: dict[str, dict] = {
    "relaxed": {
        "meals": (8.5, 13.0, 20.0),
        "slots": (SlotSpec("morning", 9.75, 3.0), SlotSpec("evening", 16.5, 2.5)),
    },
    "balanced": {
        "meals": (8.0, 13.0, 20.25),
        "slots": (SlotSpec("morning", 9.0, 3.5), SlotSpec("afternoon", 14.5, 3.0), SlotSpec("evening", 18.0, 2.0)),
    },
    "packed": {
        "meals": (7.5, 12.25, 20.5),
        "slots": (
            SlotSpec("morning", 8.5, 3.5), SlotSpec("afternoon", 13.5, 2.25),
            SlotSpec("afternoon", 16.0, 2.0), SlotSpec("evening", 18.25, 2.0),
        ),
    },
}


class BuildRequest(BaseModel):
    destination_id: str
    origin: str
    start_date: date | None = None
    duration_days: int = Field(ge=1, le=MAX_TRIP_DAYS)
    travelers: int = Field(ge=1, le=MAX_TRAVELERS)
    pace: Pace = "balanced"
    interests: list[str] = Field(default_factory=list)
    rung: int = Field(default=1, ge=0, le=LAST_RUNG)
    places: PlaceMatches
    weather: WeatherReport | None = None
    locked: dict[int, list[str]] = Field(default_factory=dict)  # day -> attraction ids to keep

    @field_validator("interests")
    @classmethod
    def _known(cls, v: list[str]) -> list[str]:
        return [i for i in v if i in INTERESTS]


def hhmm(t: float) -> str:
    total = int(round(t * 60 / 15) * 15)
    return f"{(total // 60) % 24:02d}:{total % 60:02d}"


def _ceil15(t: float) -> float:
    return math.ceil(t * 4 - 1e-9) / 4


def _mode_category(mode: str) -> str:
    return mode if mode in ("train", "flight", "bus", "cab") else "cab"


def _pick_transport(dest: Destination, origin: str, rung: Rung):
    options = dest.transport_from[origin]
    return min(options, key=lambda o: o.hours) if rung.transport == "fast" else min(options, key=lambda o: (o.one_way_per_person, o.hours))


class _DayCtx:
    def __init__(self, day: int, lo: float, hi: float, weather: DayWeather | None):
        self.day, self.lo, self.hi, self.weather = day, lo, hi, weather
        self.areas: list[str] = []
        self.types: list[str] = []


def _weather_adjust(a: Attraction, tod: str, w: DayWeather | None) -> tuple[float, str | None]:
    if w is None or a.indoor:
        return (0.5 if (w and w.rainy) else 0.0), None
    if w.rainy:
        pct = f" ({w.precip_probability:.0f}% chance)" if w.precip_probability is not None else ""
        return -4.0 - (2.0 if a.duration_hours >= FULL_DAY_HOURS else 0.0), f"Rain likely{pct}; carry rain gear or swap for an indoor plan."
    if w.hot and tod == "afternoon":
        return -2.5, f"Very hot ({w.temp_max_c:.0f}°C); carry water and shade."
    return 0.0, None


def _fmt_transit_title(origin: str, dest: str, mode: str, hours: float, outbound: bool) -> str:
    a, b = (origin, dest) if outbound else (dest, origin)
    return f"{mode.capitalize()} from {a} to {b} (about {hours:g}h)"


def build_itinerary(req: BuildRequest | dict) -> Itinerary:
    """Assemble the itinerary. Raises ToolError for unknown destinations/origins or invalid input."""
    try:
        r = req if isinstance(req, BuildRequest) else BuildRequest.model_validate(req)
    except Exception as exc:
        raise ToolError("Invalid itinerary request.") from exc
    dest = get_destination(r.destination_id)
    origin = find_origin(r.origin)
    if dest is None or origin is None or origin.name not in dest.transport_from:
        raise ToolError("Unknown destination or origin.")
    if r.places.destination_id != dest.id:
        raise ToolError("Place list does not belong to the destination.")

    rung = LADDER[r.rung]
    tier = rung.stay
    n = r.duration_days
    travelers = r.travelers
    rooms = math.ceil(travelers / 2)
    plan = PACE_PLAN[r.pace]
    b_t, l_t, d_t = plan["meals"]

    option = _pick_transport(dest, origin.name, rung)
    hours = option.hours
    arrival_abs = 7.0 + hours
    departure_abs = n * 24 - 1.0 - hours
    on_site = departure_abs - arrival_abs
    weather_by_day: dict[int, DayWeather] = {}
    if r.weather:
        for i, w in enumerate(r.weather.days):
            weather_by_day[i + 1] = w

    notes: list[str] = []
    if on_site < 4:
        notes.append(
            f"Travel takes about {hours:g}h each way by {option.mode}, which leaves almost no time at the destination. "
            "A nearer destination or a longer trip would work better."
        )
    elif hours >= 8:
        notes.append(f"Travel takes about {hours:g}h each way by {option.mode}, so the first and last days are light.")

    # ranked place lists
    atts = [s.attraction for s in r.places.attractions]
    att_score = {s.attraction.id: s.score for s in r.places.attractions}
    att_by_id = {a.id: a for a in atts}
    rests = [(s.restaurant, s.score) for s in r.places.restaurants]
    used_att: set[str] = set()
    used_rest: set[str] = set()
    allowed_tiers = {t for t, i in TIER_ORDER.items() if i <= TIER_ORDER[tier]}

    def pick_restaurant(meal: str, ctx: _DayCtx) -> Restaurant | None:
        best, best_score = None, -1e9
        for rest, sc in rests:
            if rest.id in used_rest or meal not in rest.meals or rest.tier not in allowed_tiers:
                continue
            score = sc + (0.3 if rest.area in ctx.areas else 0.0)
            if meal == "dinner":
                score += 0.2 * TIER_ORDER[rest.tier]
            if score > best_score:
                best, best_score = rest, score
        return best

    # order in which days are filled: dry days first so weather-sensitive plans land on them
    day_order = sorted(range(1, n + 1), key=lambda d: (1 if weather_by_day.get(d) and weather_by_day[d].rainy else 0, d))
    day_blocks: dict[int, list[Block]] = {d: [] for d in range(1, n + 1)}
    day_ctx: dict[int, _DayCtx] = {}
    counters: dict[int, int] = {d: 0 for d in range(1, n + 1)}

    def add(day: int, **kw) -> Block:
        counters[day] += 1
        blk = Block(id=f"d{day}-{counters[day]}", **kw)
        day_blocks[day].append(blk)
        return blk

    # --- travel + stay anchors
    out_day = 1
    arr_day = int(arrival_abs // 24) + 1
    dep_day = int(departure_abs // 24) + 1 if departure_abs > 0 else 1
    ret_arrive_day = n
    cat = _mode_category(option.mode)
    add(out_day, time_of_day="morning", start=hhmm(7.0), end=hhmm(min(7.0 + hours, 23.75) % 24 if arr_day == out_day else 23.75),
        kind="transit", category=cat, title=_fmt_transit_title(origin.name, dest.name.split(" (")[0], option.mode, hours, True),
        description=f"Outbound leg. About {option.one_way_per_person:,} per person one way.",
        cost_per_person=option.one_way_per_person, cost_total=option.one_way_per_person * travelers)
    for d in range(out_day + 1, arr_day):
        add(d, time_of_day="morning", start="00:00", end="23:45", kind="transit", category=cat, title="In transit",
            description="Travelling to the destination.")
    if 1 <= arr_day <= n:
        add(arr_day, time_of_day="afternoon", start=hhmm(arrival_abs % 24), end=hhmm((arrival_abs + 1.0) % 24), kind="stay",
            category="stay", title=f"Arrive and check in at a {TIER_LABEL[tier]} stay",
            description=f"{rooms} room(s) for {travelers} traveller(s).")
    dep_start = departure_abs - (dep_day - 1) * 24
    add(min(dep_day, n), time_of_day="evening" if dep_start >= 17 else "afternoon", start=hhmm(dep_start),
        end=hhmm(dep_start + hours if dep_day == ret_arrive_day else 23.75), kind="transit", category=cat,
        title=_fmt_transit_title(origin.name, dest.name.split(" (")[0], option.mode, hours, False),
        description=f"Return leg. About {option.one_way_per_person:,} per person one way.",
        cost_per_person=option.one_way_per_person, cost_total=option.one_way_per_person * travelers)
    for d in range(dep_day + 1, n + 1):
        add(d, time_of_day="morning", start="00:00", end="23:45", kind="transit", category=cat, title="In transit",
            description="Travelling home.")

    # --- fill each day
    nights = 0
    for d in day_order:
        base = (d - 1) * 24
        lo = max(DAY_START - 0.5, arrival_abs + 1.0 - base) if d >= arr_day else 99.0
        hi = min(DAY_END, departure_abs - 0.5 - base) if d <= dep_day else -99.0
        if d < arr_day or d > dep_day:
            lo, hi = 99.0, -99.0
        w = weather_by_day.get(d)
        ctx = _DayCtx(d, lo, hi, w)
        day_ctx[d] = ctx
        if hi - lo < 0.5:
            continue

        cursor = lo
        # breakfast is only included when the travellers are already on site by then
        if lo <= b_t + 0.25 and b_t + 0.5 <= hi:
            add(d, time_of_day="morning", start=hhmm(b_t), end=hhmm(b_t + 0.75), kind="meal", category="food",
                title="Breakfast at the hotel", description="At the property or a nearby cafe.",
                cost_per_person=dest.breakfast_pp[tier], cost_total=dest.breakfast_pp[tier] * travelers)
            cursor = b_t + 0.75

        lunch_done = False
        act_index = 0
        for slot in plan["slots"]:
            # lunch sits between the morning slots and the afternoon slots
            if not lunch_done and slot.tod != "morning":
                cursor, lunch_done = _place_meal(d, "lunch", l_t, cursor, hi, ctx, dest, tier, travelers, add, pick_restaurant, used_rest)
            start = max(slot.start, cursor)
            lunch_pending = not lunch_done and start < l_t and l_t + 0.75 <= hi
            boundary = min(hi, l_t if lunch_pending else d_t)
            avail = boundary - start
            if avail < 0.75:
                continue
            first_slot = act_index == 0
            chosen = None
            locked_ids = r.locked.get(d, [])
            if act_index < len(locked_ids) and locked_ids[act_index] in att_by_id and locked_ids[act_index] not in used_att:
                cand = att_by_id[locked_ids[act_index]]
                if rung.paid_activities or cand.cost_per_person == 0:
                    chosen = cand
            if chosen is None:
                chosen = _select(atts, att_score, used_att, slot, avail, ctx, rung, first_slot, hi - start, d > arr_day)
            if chosen is None:
                continue
            used_att.add(chosen.id)
            act_index += 1
            ctx.areas.append(chosen.area)
            ctx.types.append(chosen.type)
            _adj, note = _weather_adjust(chosen, slot.tod, ctx.weather)
            common = dict(kind="activity", category=chosen.type, title=chosen.name, description=chosen.note,
                          place_id=chosen.id, area=chosen.area, cost_per_person=chosen.cost_per_person,
                          cost_total=chosen.cost_per_person * travelers, indoor=chosen.indoor, weather_note=note)
            if _is_sunrise(chosen) and slot.tod == "morning" and d > arr_day:
                dur = min(chosen.duration_hours, 3.0)
                add(d, time_of_day="morning", start=hhmm(5.0), end=hhmm(5.0 + dur), **common)
                continue
            if chosen.duration_hours >= FULL_DAY_HOURS:
                a_start = min(start, 8.0) if chosen.duration_hours > 9 else max(start, 8.0)
                dur = min(chosen.duration_hours, hi - a_start, 10.0)
                lunch_done = True  # lunch happens during the excursion
                add(d, time_of_day="morning", start=hhmm(a_start), end=hhmm(a_start + dur), **common)
                meal = dest.generic_meal_pp[tier]
                add(d, time_of_day="afternoon", start=hhmm(a_start + dur / 2), end=hhmm(a_start + dur / 2 + 0.5), kind="meal",
                    category="food", title="Lunch during the excursion", description="Casual meal on the way.",
                    cost_per_person=meal, cost_total=meal * travelers)
                cursor = a_start + dur + 0.25
                continue
            dur = min(chosen.duration_hours, slot.cap, avail)
            a_start = _ceil15(start)
            add(d, time_of_day=slot.tod, start=hhmm(a_start), end=hhmm(a_start + dur), **common)
            cursor = a_start + dur + 0.25
        if not lunch_done:
            cursor, lunch_done = _place_meal(d, "lunch", l_t, cursor, hi, ctx, dest, tier, travelers, add, pick_restaurant, used_rest)
        # dinner (not on a departure day that leaves before evening)
        _place_meal(d, "dinner", d_t, cursor, min(hi + 0.5, DAY_END + 0.5), ctx, dest, tier, travelers, add, pick_restaurant, used_rest)

    # --- stay + local transport per day, then assemble
    days: list[Day] = []
    stay_total = local_total = 0.0
    for d in range(1, n + 1):
        base = (d - 1) * 24
        night_cost = 0.0
        if d < n and arrival_abs < base + 24 < departure_abs:
            night_cost = float(rooms * dest.stay[tier])
            nights += 1
        on_site_today = day_ctx.get(d) is not None and day_ctx[d].hi - day_ctx[d].lo >= 0.5
        local = float(dest.local_transport_per_day * math.ceil(travelers / 4)) if on_site_today else 0.0
        stay_total += night_cost
        local_total += local
        blocks = sorted(day_blocks[d], key=lambda b: (_sort_key(b), b.id))
        theme = _theme(d, blocks, arr_day, dep_day, n)
        cost = sum(b.cost_total for b in blocks) + night_cost + local
        iso = (r.start_date + timedelta(days=d - 1)).isoformat() if r.start_date else None
        days.append(Day(day=d, date=iso, theme=theme, blocks=blocks, weather=weather_by_day.get(d),
                        stay_cost=night_cost, local_transport=local, day_cost=round(cost)))

    lines = CostLines(
        transport=round(sum(b.cost_total for day in days for b in day.blocks if b.kind == "transit")),
        stay=round(stay_total),
        food=round(sum(b.cost_total for day in days for b in day.blocks if b.kind == "meal")),
        activities=round(sum(b.cost_total for day in days for b in day.blocks if b.kind in ("activity", "leisure"))),
        local_transport=round(local_total),
    )
    if r.weather and r.weather.rainy_days:
        notes.append(f"Rain is likely on day(s) {', '.join(map(str, r.weather.rainy_days))}; indoor plans were prioritised on those days.")
    if r.weather and r.weather.hot_days:
        notes.append(f"Very hot on day(s) {', '.join(map(str, r.weather.hot_days))}; afternoons avoid strenuous outdoor plans.")
    if r.start_date and r.start_date.month in dest.avoid_months:
        notes.append(f"Heads up: this is off-season for {dest.name.split(' (')[0]} ({dest.avoid_reason}).")

    return Itinerary(
        destination_id=dest.id, destination_name=dest.name, origin=origin.name,
        start_date=r.start_date.isoformat() if r.start_date else None, duration_days=n, travelers=travelers,
        pace=r.pace, stay_tier=tier, transport_mode=option.mode, rooms=rooms, nights=nights, days=days,
        cost_lines=lines, total_cost=float(sum(lines.model_dump().values())), notes=notes,
    )


def _place_meal(d, meal, nominal, cursor, hi, ctx, dest, tier, travelers, add, pick_restaurant, used_rest):
    """Place a lunch or dinner block if it fits in the day's window. Returns (new cursor, placed)."""
    start = max(nominal, cursor)
    latest_start = 15.0 if meal == "lunch" else DAY_END
    if start > latest_start or start + 0.75 > hi + 0.01 or hi - ctx.lo < 0.5:
        return cursor, False
    rest = pick_restaurant(meal, ctx)
    tod = "afternoon" if meal == "lunch" else "evening"
    if rest is not None:
        used_rest.add(rest.id)
        ctx.areas.append(rest.area)
        add(d, time_of_day=tod, start=hhmm(_ceil15(start)), end=hhmm(_ceil15(start) + 1.0), kind="meal", category="food",
            title=f"{meal.capitalize()} at {rest.name}", description=f"{rest.cuisine}. Try: {rest.signature}.",
            place_id=rest.id, area=rest.area, cost_per_person=rest.cost_per_person, cost_total=rest.cost_per_person * travelers)
    else:
        cost = dest.generic_meal_pp[tier]
        add(d, time_of_day=tod, start=hhmm(_ceil15(start)), end=hhmm(_ceil15(start) + 1.0), kind="meal", category="food",
            title=f"{meal.capitalize()} at a local eatery", description="Casual local meal near where you are.",
            cost_per_person=cost, cost_total=cost * travelers)
    return _ceil15(start) + 1.0, True


def _select(atts, score, used, slot, avail, ctx, rung, first_slot, day_left, after_arrival_day) -> Attraction | None:
    best, best_score = None, -1e9
    for a in atts:
        if a.id in used:
            continue
        if not rung.paid_activities and a.cost_per_person > 0:
            continue
        full = a.duration_hours >= FULL_DAY_HOURS
        if _is_sunrise(a) and not (after_arrival_day and slot.tod == "morning" and first_slot):
            continue
        if full:
            if not first_slot or slot.tod != "morning" or day_left < min(a.duration_hours, 9.5):
                continue
        elif min(a.duration_hours, slot.cap) > avail + 1e-9:
            continue
        s = score[a.id]
        if a.best_time == slot.tod:
            s += 0.5
        elif a.best_time != "any":
            s -= 2.0
        if a.area in ctx.areas:
            s += 0.4
        s -= 0.3 * ctx.types.count(a.type)
        adj, _ = _weather_adjust(a, slot.tod, ctx.weather)
        s += adj
        if s > best_score:
            best, best_score = a, s
    return best


def _is_sunrise(a: Attraction) -> bool:
    return "sunrise" in a.name.lower()


def _sort_key(b: Block) -> float:
    h, m = b.start.split(":")
    return int(h) + int(m) / 60


def _theme(day: int, blocks: list[Block], arr_day: int, dep_day: int, n: int) -> str:
    acts = [b.title for b in blocks if b.kind == "activity"]
    if not acts:
        if day < arr_day or (day > dep_day):
            return "Travel day"
        return "Arrival and settling in" if day == arr_day else "Departure"
    lead = " and ".join(a for a in acts[:2])
    prefix = "Arrival: " if day == arr_day and day != 1 else ""
    if day == 1 and day == arr_day:
        prefix = "Arrival: "
    if day == n and day == dep_day:
        prefix = "Last day: "
    return (prefix + lead)[:90]


def diff_itineraries(old: Itinerary | dict, new: Itinerary | dict) -> list[str]:
    """Plain-language list of what changed between two itinerary versions."""
    o = old if isinstance(old, Itinerary) else Itinerary.model_validate(old)
    nw = new if isinstance(new, Itinerary) else Itinerary.model_validate(new)
    out: list[str] = []
    if o.destination_id != nw.destination_id:
        out.append(f"Destination changed from {o.destination_name} to {nw.destination_name}.")
    if o.duration_days != nw.duration_days:
        out.append(f"Trip length changed from {o.duration_days} to {nw.duration_days} days.")
    if o.travelers != nw.travelers:
        out.append(f"Travellers changed from {o.travelers} to {nw.travelers}.")
    if o.pace != nw.pace:
        out.append(f"Pace changed from {o.pace} to {nw.pace}.")
    if o.stay_tier != nw.stay_tier:
        out.append(f"Stay changed from {TIER_LABEL[o.stay_tier]} to {TIER_LABEL[nw.stay_tier]}.")
    if o.transport_mode != nw.transport_mode:
        out.append(f"Transport changed from {o.transport_mode} to {nw.transport_mode}.")

    def acts(it: Itinerary) -> dict[str, str]:
        return {b.place_id: b.title for d in it.days for b in d.blocks if b.kind == "activity" and b.place_id}

    oa, na = acts(o), acts(nw)
    added = [t for k, t in na.items() if k not in oa]
    removed = [t for k, t in oa.items() if k not in na]
    if added:
        out.append("Added: " + ", ".join(added[:6]) + ("…" if len(added) > 6 else "") + ".")
    if removed:
        out.append("Removed: " + ", ".join(removed[:6]) + ("…" if len(removed) > 6 else "") + ".")
    if o.total_cost != nw.total_cost:
        out.append(f"Total cost changed from ₹{o.total_cost:,.0f} to ₹{nw.total_cost:,.0f}.")
    return out
